#!/usr/bin/env bash

eslint --ext .html --ext .js --format node_modules/eslint-friendly-formatter src

# https://github.com/eslint/eslint/issues/5040#issuecomment-186041504
if [[ -d "${CIRCLE_TEST_REPORTS}" ]]; then
  mkdir -p "${CIRCLE_TEST_REPORTS}/style"
  eslint --ext .html --ext .js --format junit src > "${CIRCLE_TEST_REPORTS}/style/eslint.xml"
fi
